package:
  name: libxxf86dga
  version: 1.1.3

source:
  fn: libXxf86dga-1.1.3.tar.bz2
  url: http://xorg.mirrors.pair.com/X11R7.7/src/lib/libXxf86dga-1.1.3.tar.bz2

build:
  number: 0

requirements:
  build:
    - xf86dgaproto ==2.1
    - libx11 ==1.5.0
    - libxext ==1.3.1

  run:
    - xf86dgaproto ==2.1
    - libx11 ==1.5.0
    - libxext ==1.3.1

about:
  home: http://www.x.org/archive/X11R7.7
  license: MIT License
