package:
  name: randrproto
  version: 1.3.2

source:
  fn: randrproto-1.3.2.tar.bz2
  url: http://xorg.mirrors.pair.com/X11R7.7/src/proto/randrproto-1.3.2.tar.bz2

build:
  number: 0

about:
  home: http://www.x.org/archive/X11R7.7
  license: MIT License
