package:
  name: kbproto
  version: 1.0.6

source:
  fn: kbproto-1.0.6.tar.bz2
  url: http://xorg.mirrors.pair.com/X11R7.7/src/proto/kbproto-1.0.6.tar.bz2

build:
  number: 0

about:
  home: http://www.x.org/archive/X11R7.7
  license: MIT License
