package:
  name: xcb-util-wm
  version: 0.4.1

source:
  fn: xcb-util-wm-0.4.1.tar.bz2
  url: http://xcb.freedesktop.org/dist/xcb-util-wm-0.4.1.tar.bz2

build:
  number: 1

requirements:
  build:
    - libxcb ==1.11
    - libpthread-stubs
 
  run: 
    - libxcb ==1.11
    - libpthread-stubs

about:
  home: http://www.x.org/archive/X11R7.7
  license: MIT License
