package:
  name: libfs
  version: 1.0.4

source:
  fn: libFS-1.0.4.tar.bz2
  url: http://xorg.mirrors.pair.com/X11R7.7/src/lib/libFS-1.0.4.tar.bz2

build:
  number: 0

requirements:
  build:
    - fontsproto ==2.1.2
    - xproto ==7.0.23
    - xtrans ==1.2.7

  run:
    - fontsproto ==2.1.2
    - xproto ==7.0.23
    - xtrans ==1.2.7

about:
  home: http://www.x.org/archive/X11R7.7
  license: MIT License
