package:
  name: libxres
  version: 1.0.6

source:
  fn: libXres-1.0.6.tar.bz2
  url: http://xorg.mirrors.pair.com/X11R7.7/src/lib/libXres-1.0.6.tar.bz2

build:
  number: 0

requirements:
  build:
    - resourceproto ==1.2.0
    - libx11 ==1.5.0
    - libxext ==1.3.1

  run:
    - resourceproto ==1.2.0
    - libx11 ==1.5.0
    - libxext ==1.3.1

about:
  home: http://www.x.org/archive/X11R7.7
  license: MIT License
