package:
  name: xineramaproto
  version: 1.2.1

source:
  fn: xineramaproto-1.2.1.tar.bz2
  url: http://xorg.mirrors.pair.com/X11R7.7/src/proto/xineramaproto-1.2.1.tar.bz2

build:
  number: 0

about:
  home: http://www.x.org/archive/X11R7.7
  license: MIT License
