package:
  name: libfontenc
  version: 1.1.1

source:
  fn: libfontenc-1.1.1.tar.bz2
  url: http://xorg.mirrors.pair.com/X11R7.7/src/lib/libfontenc-1.1.1.tar.bz2

build:
  number: 0

requirements:
  build:
    - xproto ==7.0.23
 
  run:
    - xproto ==7.0.23

about:
  home: http://www.x.org/archive/X11R7.7
  license: MIT License
