package:
  name: libxaw
  version: 1.0.11

source:
  fn: libXaw-1.0.11.tar.bz2
  url: http://xorg.mirrors.pair.com/X11R7.7/src/lib/libXaw-1.0.11.tar.bz2

build:
  number: 0

requirements: 
  build: 
    - xextproto ==7.2.1
    - xproto ==7.0.23
    - xtrans ==1.2.7
    - libxext ==1.3.1
    - libxt ==1.1.3
    - libxmu ==1.1.1
    - libxpm ==3.5.10
  run: 
    - xextproto ==7.2.1
    - xproto ==7.0.23
    - xtrans ==1.2.7
    - libxext ==1.3.1
    - libxt ==1.1.3
    - libxmu ==1.1.1
    - libxpm ==3.5.10

about:
  home: http://www.x.org/archive/X11R7.7
  license: MIT License
