package:
  name: xcb-util
  version: 0.4.0

source:
  fn: xcb-util-0.4.0.tar.bz2
  url: http://xcb.freedesktop.org/dist/xcb-util-0.4.0.tar.bz2

build:
  number: 1

requirements:
  build: 
    - libxcb ==1.11
    - libpthread-stubs
 
  run: 
    - libxcb ==1.11
    - libpthread-stubs

about:
  home: http://www.x.org/archive/X11R7.7
  license: MIT License
