package:
  name: resourceproto
  version: 1.2.0

source:
  fn: resourceproto-1.2.0.tar.bz2
  url: http://xorg.mirrors.pair.com/X11R7.7/src/proto/resourceproto-1.2.0.tar.bz2

build:
  number: 0

about:
  home: http://www.x.org/archive/X11R7.7
  license: MIT License
