package:
  name: libxmu
  version: 1.1.1

source:
  fn: libXmu-1.1.1.tar.bz2
  url: http://xorg.mirrors.pair.com/X11R7.7/src/lib/libXmu-1.1.1.tar.bz2

build:
  number: 0

requirements:
  build:
    - xextproto ==7.2.1
    - libx11 ==1.5.0
    - libxext ==1.3.1
    - libxt ==1.1.3

  run:
    - xextproto ==7.2.1
    - libx11 ==1.5.0
    - libxext ==1.3.1
    - libxt ==1.1.3

about:
  home: http://www.x.org/archive/X11R7.7
  license: MIT License
