package:
  name: libxi
  version: 1.6.1

source:
  fn: libXi-1.6.1.tar.bz2
  url: http://xorg.mirrors.pair.com/X11R7.7/src/lib/libXi-1.6.1.tar.bz2

build:
  number: 0

requirements: 
  build: 
    - inputproto ==2.2
    - libxext ==1.3.1
  run: 
    - inputproto ==2.2
    - libxext ==1.3.1

about:
  home: http://www.x.org/archive/X11R7.7
  license: MIT License
