package:
  name: libxv
  version: 1.0.7

source:
  fn: libXv-1.0.7.tar.bz2
  url: http://xorg.mirrors.pair.com/X11R7.7/src/lib/libXv-1.0.7.tar.bz2

build:
  number: 0

requirements:
  build:
    - videoproto ==2.3.1
    - libx11 ==1.5.0
    - libxext ==1.3.1
    - libxi ==1.6.1

  run:
    - videoproto ==2.3.1
    - libx11 ==1.5.0
    - libxext ==1.3.1
    - libxi ==1.6.1

about:
  home: http://www.x.org/archive/X11R7.7
  license: MIT License
