package:
  name: libxtst
  version: 1.2.1

source:
  fn: libXtst-1.2.1.tar.bz2
  url: http://xorg.mirrors.pair.com/X11R7.7/src/lib/libXtst-1.2.1.tar.bz2

build:
  number: 0

requirements:
  build:
    - recordproto ==1.14.2
    - libx11 ==1.5.0
    - libxext ==1.3.1
    - libxi ==1.6.1

  run:
    - recordproto ==1.14.2
    - libx11 ==1.5.0
    - libxext ==1.3.1
    - libxi ==1.6.1

about:
  home: http://www.x.org/archive/X11R7.7
  license: MIT License
