package:
  name: libxft
  version: 2.3.1

source:
  fn: libXft-2.3.1.tar.bz2
  url: http://xorg.mirrors.pair.com/X11R7.7/src/lib/libXft-2.3.1.tar.bz2

build:
  number: 1

requirements:
  build:
    - fontconfig 2*
    - freetype ==2.4.9
    - libxrender ==0.9.7

  run:
    - fontconfig 2*
    - freetype ==2.4.9
    - libxrender ==0.9.7

about:
  home: http://www.x.org/archive/X11R7.7
  license: MIT License
