package:
  name: libxxf86vm
  version: 1.1.2

source:
  fn: libXxf86vm-1.1.2.tar.bz2
  url: http://xorg.mirrors.pair.com/X11R7.7/src/lib/libXxf86vm-1.1.2.tar.bz2

build:
  number: 0

requirements:
  build:
    - xf86vidmodeproto ==2.3.1
    - libx11 ==1.5.0
    - libxext ==1.3.1
 
  run: 
    - xf86vidmodeproto ==2.3.1
    - libx11 ==1.5.0
    - libxext ==1.3.1

about:
  home: http://www.x.org/archive/X11R7.7
  license: MIT License
