package:
  name: libxinerama
  version: 1.1.2

source:
  fn: libXinerama-1.1.2.tar.bz2
  url: http://xorg.mirrors.pair.com/X11R7.7/src/lib/libXinerama-1.1.2.tar.bz2

build:
  number: 0

requirements:
  build:
    - xextproto ==7.2.1
    - xineramaproto ==1.2.1
    - libx11 ==1.5.0
    - libxext ==1.3.1

  run:
    - xextproto ==7.2.1
    - xineramaproto ==1.2.1
    - libx11 ==1.5.0
    - libxext ==1.3.1

about:
  home: http://www.x.org/archive/X11R7.7
  license: MIT License
