package:
  name: compositeproto
  version: 0.4.2

source:
  fn: compositeproto-0.4.2.tar.bz2
  url: http://xorg.mirrors.pair.com/X11R7.7/src/proto/compositeproto-0.4.2.tar.bz2

build:
  number: 0

about:
  home: http://www.x.org/archive/X11R7.7
  license: MIT License
