package:
  name: xextproto
  version: 7.2.1

source:
  fn: xextproto-7.2.1.tar.bz2
  url: http://xorg.mirrors.pair.com/X11R7.7/src/proto/xextproto-7.2.1.tar.bz2

build:
  number: 1

about:
  home: http://www.x.org/archive/X11R7.7
  license: MIT License
