package:
  name: libice
  version: 1.0.8

source:
  fn: libICE-1.0.8.tar.bz2
  url: http://xorg.mirrors.pair.com/X11R7.7/src/lib/libICE-1.0.8.tar.bz2

build:
  number: 0

requirements: 
  build: 
    - xproto ==7.0.23
    - xtrans ==1.2.7
  run: 
    - xproto ==7.0.23
    - xtrans ==1.2.7

about:
  home: http://www.x.org/archive/X11R7.7
  license: MIT License
