package:
  name: xorg-libs
  version: 7.7+1  # Just following the standard nomenclature used on distros

build:
  number: 0

requirements:
  build:
    - libxcb ==1.11
    - libdmx ==1.1.2
    - libfontenc ==1.1.1
    - libfs ==1.0.4
    - libice ==1.0.8
    - libpciaccess ==0.13.1
    - libsm ==1.2.1
    - libx11 ==1.5.0
    - libxau ==1.0.7
    - libxaw ==1.0.11
    - libxcomposite ==0.4.3
    - libxcursor ==1.1.13
    - libxdamage ==1.1.3
    - libxdmcp ==1.1.1
    - libxext ==1.3.1
    - libxfixes ==5.0
    - libxfont ==1.4.5
    - libxft ==2.3.1
    - libxi ==1.6.1
    - libxinerama ==1.1.2
    - libxkbfile ==1.0.8
    - libxmu ==1.1.1
    - libxpm ==3.5.10
    - libxrandr ==1.3.2
    - libxrender ==0.9.7
    - libxres ==1.0.6
    - libxt ==1.1.3
    - libxtst ==1.2.1
    - libxv ==1.0.7
    - libxvmc ==1.0.7
    - libxxf86dga ==1.1.3
    - libxxf86vm ==1.1.2
    - xcb-util ==0.4.0
    - xcb-util-image ==0.4.0
    - xcb-util-keysyms ==0.4.0
    - xcb-util-renderutil ==0.3.9
    - xcb-util-wm  ==0.4.1
    - xtrans ==1.2.7

  run:
    - libxcb ==1.11
    - libdmx ==1.1.2
    - libfontenc ==1.1.1
    - libfs ==1.0.4
    - libice ==1.0.8
    - libpciaccess ==0.13.1
    - libsm ==1.2.1
    - libx11 ==1.5.0
    - libxau ==1.0.7
    - libxaw ==1.0.11
    - libxcomposite ==0.4.3
    - libxcursor ==1.1.13
    - libxdamage ==1.1.3
    - libxdmcp ==1.1.1
    - libxext ==1.3.1
    - libxfixes ==5.0
    - libxfont ==1.4.5
    - libxft ==2.3.1
    - libxi ==1.6.1
    - libxinerama ==1.1.2
    - libxkbfile ==1.0.8
    - libxmu ==1.1.1
    - libxpm ==3.5.10
    - libxrandr ==1.3.2
    - libxrender ==0.9.7
    - libxres ==1.0.6
    - libxt ==1.1.3
    - libxtst ==1.2.1
    - libxv ==1.0.7
    - libxvmc ==1.0.7
    - libxxf86dga ==1.1.3
    - libxxf86vm ==1.1.2
    - xcb-util ==0.4.0
    - xcb-util-image ==0.4.0
    - xcb-util-keysyms ==0.4.0
    - xcb-util-renderutil ==0.3.9
    - xcb-util-wm  ==0.4.1
    - xtrans ==1.2.7

about:
  home: http://www.x.org/archive/X11R7.7
  license: MIT License
  summary: >
    This is just a meta package to group all xorg libraries.
    Qt5 needs a recent libx11 and libxcb, but those brings several dependencies all their versions
    should be compatible with each other (we cannot mix some xorg libs compiles by us with some from the system)
