package:
  name: libxrandr
  version: 1.3.2

source:
  fn: libXrandr-1.3.2.tar.bz2
  url: http://xorg.mirrors.pair.com/X11R7.7/src/lib/libXrandr-1.3.2.tar.bz2

build:
  number: 0

requirements:
  build:
    - randrproto ==1.3.2
    - libx11 ==1.5.0
    - libxext ==1.3.1
    - libxrender ==0.9.7

  run:
    - randrproto ==1.3.2
    - libx11 ==1.5.0
    - libxext ==1.3.1
    - libxrender ==0.9.7

about:
  home: http://www.x.org/archive/X11R7.7
  license: MIT License
