package:
  name: libxpm
  version: 3.5.10

source:
  fn: libXpm-3.5.10.tar.bz2
  url: http://xorg.mirrors.pair.com/X11R7.7/src/lib/libXpm-3.5.10.tar.bz2

build:
  number: 0

requirements:
  build:
    - xproto ==7.0.23
    - libx11 ==1.5.0
 
  run:
    - xproto ==7.0.23
    - libx11 ==1.5.0

about:
  home: http://www.x.org/archive/X11R7.7
  license: MIT License
