package:
  name: libxext
  version: 1.3.1

source:
  fn: libXext-1.3.1.tar.bz2
  url: http://xorg.mirrors.pair.com/X11R7.7/src/lib/libXext-1.3.1.tar.bz2

build:
  number: 0

requirements:
  build:
    - xextproto ==7.2.1
    - xproto ==7.0.23
    - libx11 ==1.5.0
 
  run: 
    - xextproto ==7.2.1
    - xproto ==7.0.23
    - libx11 ==1.5.0

about:
  home: http://www.x.org/archive/X11R7.7
  license: MIT License
