package:
  name: xtrans
  version: 1.2.7

source:
  fn: xtrans-1.2.7.tar.bz2
  url: http://xorg.mirrors.pair.com/X11R7.7/src/lib/xtrans-1.2.7.tar.bz2

build:
  number: 1

about:
  home: http://www.x.org/archive/X11R7.7
  license: MIT License
