package:
  name: libxcomposite
  version: 0.4.3

source:
  fn: libXcomposite-0.4.3.tar.bz2
  url: http://xorg.mirrors.pair.com/X11R7.7/src/lib/libXcomposite-0.4.3.tar.bz2

build:
  number: 0

requirements: 
  build: 
    - compositeproto ==0.4.2
    - kbproto ==1.0.6
    - libx11 ==1.5.0
    - libxfixes ==5.0
  run: 
    - compositeproto ==0.4.2
    - kbproto ==1.0.6
    - libx11 ==1.5.0
    - libxfixes ==5.0

about:
  home: http://www.x.org/archive/X11R7.7
  license: MIT License
