package:
  name: libdmx
  version: 1.1.2

source:
  fn: libdmx-1.1.2.tar.bz2
  url: http://xorg.mirrors.pair.com/X11R7.7/src/lib/libdmx-1.1.2.tar.bz2

build:
  number: 0

requirements: 
  build: 
    - dmxproto ==2.3.1
    - xextproto ==7.2.1
    - libxext ==1.3.1
    - libx11 ==1.5.0
  run: 
    - dmxproto ==2.3.1
    - xextproto ==7.2.1
    - libxext ==1.3.1
    - libx11 ==1.5.0


about:
  home: http://www.x.org/archive/X11R7.7
  license: MIT License
