package:
  name: libxdamage
  version: 1.1.3

source:
  fn: libXdamage-1.1.3.tar.gz
  url: http://xorg.mirrors.pair.com/X11R7.7/src/lib/libXdamage-1.1.3.tar.gz

build:
  number: 0

requirements:
  build:
    - libx11 ==1.5.0
    - libxfixes ==5.0
    - damageproto ==1.2.1
    - fixesproto ==5.0
    - xproto ==7.0.23
    - xextproto ==7.2.1
 
  run: 
    - libx11 ==1.5.0
    - libxfixes ==5.0
    - damageproto ==1.2.1
    - fixesproto ==5.0
    - xproto ==7.0.23
    - xextproto ==7.2.1

about:
  home: http://www.x.org/archive/X11R7.7
  license: MIT License
